DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS announcement;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE announcement (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  body TEXT NOT NULL,
  price INTEGER NOT NULL,
  image TEXT NOT NULL,
  status TEXT DEFAULT 'active'
);