DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS products;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  price INTEGER NOT NULL,
  title TEXT NOT NULL,
  image TEXT NOT NULL,
  status TEXT DEFAULT 'active'
);