DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS paypal;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE,
  username TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  password TEXT NOT NULL
);

CREATE TABLE announcement (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT UNIQUE NOT NULL,
  body TEXT NOT NULL,
  price INTEGER NOT NULL,
  status TEXT DEFAULT 'active',
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  images TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE paypal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    paypalid TEXT NOT NULL,
    customer TEXT NOT NULL,
    price INTEGER,
    status TEXT NOT NULL
);